@host= http://localhost:3000
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2wiOiJmYW1pbGlhciIsImV4cCI6MTc1MTQ5NTkzNSwiaWF0IjoxNzUxMDYzOTM1fQ.YiCp2k9wMuQj-l0q3qzKXCwFe9a6_aXy7Hd6Ox9KrZA

############
# USUARIOS #
############

###
GET {{host}}/api/usuarios/1

###
POST {{host}}/api/usuarios/register
Content-Type: application/json

{
    "name":"Juan",
    "lastname":"Pérez",
    "email":"carlos.ramirez@example.com",
    "phone":"0991234567",
    "password": "Test"
}

###
POST {{host}}/api/usuarios/login
Content-Type: application/json

{
    "email": "carlos.ramirez@example.com",
    "password": "Test"
}

#################
# PERSONA MAYOR #
#################

###
GET {{host}}/api/personas-mayores/1
Authorization: {{token}}

###
GET {{host}}/api/personas-mayores
Authorization: {{token}}

###
POST {{host}}/api/personas-mayores
Content-Type: application/json
Authorization: {{token}}

{
  "nombre": "Cesar",
  "apellido": "Ho",
  "fecha_nacimiento": "1950-05-10",
  "genero": "Masculino",
  "movilidad": "Limitada",
  "condiciones_medicas": "Diabetes",
  "notas_generales": "Requiere atención especial",
  "relacion": "familiar"
}


###
PUT {{host}}/api/personas-mayores/5
Content-Type: application/json
Authorization: {{token}}

{
  "nombre": "Juana",
  "apellido": "Pérez",
  "fecha_nacimiento": "1945-03-15",
  "genero": "femenino",
  "movilidad": "limitada",
  "condiciones_medicas": "hipertensión",
  "notas_generales": "Requiere control mensual"
}

###
DELETE {{host}}/api/personas-mayores/4
Authorization: {{token}}

###############
# ACTIVIDADES #
###############

###
GET {{host}}/api/actividades/persona-mayor/2
Authorization: {{token}}

###
GET {{host}}/api/actividades/3
Authorization: {{token}}

###
POST {{host}}/api/actividades
Content-Type: application/json
Authorization: {{token}}

{
  "persona_mayor_id": 2,
  "nombre": "Training",
  "categoria": "ocio",
  "descripcion": "Estiramientos suaves de 30 minutos",
  "es_recurrente": 0
}

###
PUT {{host}}/api/actividades/5
Content-Type: application/json
Authorization: {{token}}

{
  "nombre": "Ejercicio de memoria 2",
  "categoria": "terapia",
  "descripcion": "Actividades para estimular la memoria y concentración",
  "es_recurrente": 1
}

###
DELETE {{host}}/api/actividades/6
Authorization: {{token}}


###############
# EVENTOACTIVIDAD #
###############
POST {{host}}/api/evento-actividad
Content-Type: application/json
Authorization: {{token}}

{
  "actividad_id": 5,
  "fecha_inicio": "2025-07-01 09:00:00",
  "fecha_fin": "2025-07-01 10:00:00",
  "recordatorio": true
}

###
GET {{host}}/api/evento-actividad
Authorization: {{token}}

###
GET {{host}}/api/evento-actividad/11
Authorization: {{token}}